title: Developer Experience
description: This site is a working collection of everything I have learned about Developer Experience along my journey.
baseurl: "/dev-ex"
url: "https://bandokal.github.io"


remote_theme: just-the-docs/just-the-docs

author:
  name   : "Jason Bandy"
  avatar : "/assets/images/jb-head.png"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BandoKal"
